### ISSUE TITLE
Temporary install in tandem with homebrew?

### ISSUE THREAD

**Issue by larryhynes** [cmacrae/saveosx#10]
I'm keen to give this project a try, but am *heavily* invested in homebrew to manage my current setup and don't want to do a 'hard' switch; I would like to dip my toe in the pkgsrc water and see what I think.

I have, through much trial and error, got an X(quartz)11 setup running (on Yosemite) that I'm happy with, using i3, urxvt, mupdf and sxiv, so you can see where I'm headed! :smile: (Much as I would love to just set up an OpenBSD box I'm afraid I'm tied to Apple for the immediate future.)

To illustrate the scale of my pickle, a 'dry run' of the brew uninstall script runs to 11,175 lines.

What steps would I need to take to get a taste of your project on this machine without uninstalling brew? (I know the bootstrap script bails immediately on finding `brew`, and I totally get that, but I'm quite happy to get my hands dirty if you can point me towards a reasonable sane method of getting the two to live together for a week or two while I play with stuff.)

**Comment by larryhynes** [comment]
Looking through the `bootstrap` script, I think I'll be able to get something sorted.

**Comment by cmacrae** [comment]
Hey @larryhynes, thanks for your interest in the project.

Cool, simply removing the check for the brew binary should do it 👍🏻

Let me know if you need anything!

**Comment by deitch** [comment]
Can you add an option like `-f` or `--force` (or maybe `--brew`) to allow you to run with brew installed?

**Comment by cmacrae** [comment]
@deitch: Sure, I like this idea - you caught me at a good time, I'll add this now :+1:

**Comment by deitch** [comment]
Thanks, sir. 

BTW, another nice thing. It sets the PATH correctly, but not in the current shell. Can it either warn about it, or re-source the necessary profile files?

**Comment by cmacrae** [comment]
There ya go @deitch, cfb3019 should do what you want :)

Yeah, that last one is kinda awkward. I added in the re-evaluation of the PATH via `path_helper`, but as it's in a subshell, it seems it's being left in that session; hence the need to open a new shell.

I'll add a note at the end of the completion message.

**Comment by deitch** [comment]
@cmacrae awesome! What speed!

Yeah, I know it is tricky. You cannot source it because you are in a shell. But as you said, documentation is good enough. As long as no one is surprised.

**Comment by cmacrae** [comment]
@deitch Haha ;)

Yeah, I certainly agree - I added it to the final screen message in yellow. Hopefully the bright colours will suffice! Also cleaned up that code from my previous commits...

Enjoy! Thanks very much for your suggestions. Don't hesitate to drop any other ideas/contributions you may have :+1:
