### ISSUE TITLE
ffmpeg library issues with freetype

### ISSUE THREAD

**Issue by Phlogi** [cmacrae/saveosx#11]
ffmpeg
```
dyld: Library not loaded: /opt/X11/lib/libfreetype.6.dylib
  Referenced from: /opt/pkg/lib/libass.5.dylib
  Reason: Incompatible library version: libass.5.dylib requires version 18.0.0 or later, but libfreetype.6.dylib provides version 17.0.0
[1]    6281 trace trap (core dumped)  ffmpeg
```

When I add this to my env:
`DYLD_LIBRARY_PATH=/opt/pkg/lib`
I get:
```
dyld: Symbol not found: _sqlite3_intarray_bind
  Referenced from: /System/Library/Frameworks/CoreData.framework/Versions/A/CoreData
  Expected in: /opt/pkg/lib/libsqlite3.dylib
 in /System/Library/Frameworks/CoreData.framework/Versions/A/CoreData
[1]    6477 trace trap (core dumped)  ffmpeg

```

**Comment by cmacrae** [comment]
This is not related to `saveosx` - please report this to @jperkin over at **[joyent/pkgsrc-joyent](https://github.com/joyent/pkgsrc-joyent/issues).**

When you raise the issue over there, make sure you provide more details than you have above (be sure to state you're running into this issue with Darwin, and the pkgsrc quarter you're installing from).
