### ISSUE TITLE
Outdated `path` on http://saveosx.org/pkgin-howto

### ISSUE THREAD

**Issue by weakish** [cmacrae/saveosx#13]
> Add /usr/pkg/bin and /usr/pkg/sbin to your $PATH

>     $ PATH=/usr/pkg/bin:/usr/pkg/sbin:$PATH

> Add /usr/pkg/man to your $MANPATH

>    $ MANPATH=/usr/pkg/man:$MANPATH

-- http://saveosx.org/pkgin-howto

Paths have been updated to `/opt/pkg/bin` and `/opt/pkg/share/man`.

**Comment by cmacrae** [comment]
Thanks @weakish - this site isn't maintained anymore. It'll either be taken down shortly, or simply redirect to this project's GitHub page.
