### ISSUE TITLE
Building from source

### ISSUE THREAD

**Issue by numinasthmatic** [cmacrae/saveosx#15]
I would like to be able to build some packages from source.  However, there seems to be a division between this install for binary packages and the NetBSD pkgsrc install described in the joyent/pkgsrc document.  (In fact, the pkgsrc/doc/pkgsrc.txt document describes the NetBSD download sites, rather than the joyent site.

I have downloaded and bootstrapped the full pkgsrc sources, but I cannot get pkg_add to work, so I was wondering whether it is possible to extend the saveosx install to build from source.

**Comment by cmacrae** [comment]
Save OS X is intended as an easy bootstrap to get up and running with binary packages from pkgsrc.

Bootstrapping pkgsrc for building packages from source should be followed as outlined in the official documentation, and only takes a few short steps. Thus, I feel it is unnecessary and out of scope for Save OS X.
