### ISSUE TITLE
PATH order?

### ISSUE THREAD

**Issue by jf** [cmacrae/saveosx#16]
Just wondering, but with the way things are set up with the PATH, the system paths are preferred over pkgsrc's paths when searching for binaries. Is there a reason for this? Generally, binaries would probably be in only one of two places (system, vs pkgsrc), but there are a few exceptions: perl, python2.7... and most notably,`less`.

Why do I care? Because in the case of duplicates, I want my explicity-installed binary to take precedence over the system-provided version. In the case of `less`, if the system path is preferred, I end up using the stupid `less` provided by OS X. OS X's `less` is crippled, and has no support (`man less` lies! \<expletive, expletive Apple>) at all for `lesskey`. It sounds crazy, but I have to install some packaging system (to be sure, this isn't the only reason why I am, but just saying) just to get a proper `less` with support for `lesskey`.

**Comment by jf** [comment]
sorry, I just realized somebody has asked this before (#4)! Closing this then...

**Comment by jf** [comment]
Sorry, but a follow-up question that's relevant to this: will setting the PATH up in this way result in any problems internally with binaries installed by pkgsrc? Say for example, binary X from pkgsrc relies on binary Y from pkgsrc, but then ends up calling binary Y from the system instead.

**Comment by cmacrae** [comment]
Hey @jf, no problem :+1: 
As far as my experience goes: there shouldn't be any problems introduced by setting the PATH up to search in pkgsrc first. I've been using that set-up since I started the project and haven't encountered any issues. Feel free to re-open this if you feel there's anything more I can do :)

**Comment by jf** [comment]
Thanks, @cmacrae, I appreciate the patience and the info. I was thinking of proposing to edit `/etc/paths` instead of placing files in `/etc/paths.d` for more control over the search order/path... but I guess if the goal is to have pkgsrc's directories be at the end of the search path, it doesnt matter that much.

**Comment by cmacrae** [comment]
No worries! Yeah, using paths.d is a better approach, in my opinion. It's really the correct place for 3rd party software to place their path eval files.
