### ISSUE TITLE
Curling for files should verify what was downloaded

### ISSUE THREAD

**Issue by christiank** [cmacrae/saveosx#2]
I set the bootstrap script into motion. When the time came to curl for pkgsrc, my connection timed out and left behind an incomplete /tmp/bootstrap.tar.gz. However, the bootstrap script merely checks for the existence of /tmp/bootstrap.tar.gz, which isn't sufficient.

It would be pretty cool to also get a hold of, say, the SHA256 of the pkgsrc tarball, at least. That way we don't leave behind stale files, and it's more secure this way, too.

Or maybe the real problem is that saferun() is just too aggressive -- it exits immediately and doesn't do any cleanup.

**Comment by cmacrae** [comment]
Certainly agree. I'll be happy to implement a sum check. The saferun function is not supposed to be smart, and exit upon anything other than exit 0.
I'll take a look at this tomorrow

**Comment by cmacrae** [comment]
@christiank I've implemented this in 7d20e11. Mind testing? :)

**Comment by cmacrae** [comment]
Well, I've testing this quite a bit, and all seems well.  
I'll consider this fixed, but please let me know right away if you run into any trouble.  

Thanks for the contribution and your interest in the project! :)
