### ISSUE TITLE
Paths order

### ISSUE THREAD

**Issue by q-b** [cmacrae/saveosx#4]
Hi,

While it looks like your doing things the right way, i.e. setting additional paths in `/etc/paths.d/saveosx`, the resulting `$PATH` includes the directories as the last items.
If I install an updated version of `git`, the one in `/usr/bin/` will still be called, instead of the one in `/usr/pkg/...`.
Maybe the paths should be explicitly set in the `.shellrc` instead?

**Comment by cmacrae** [comment]
I took this approach intentionally :)
It's important to have the base binaries in OS X found before those installed by `pkgsrc` - it should be as unobtrusive as possible. If the user wants to evaluate the `pkgsrc` binary path first, they can do so manually.
