### ISSUE TITLE
pkgin: Could not fetch http...

### ISSUE THREAD

**Issue by mak42** [cmacrae/saveosx#5]
I keep getting this message on update

> pkgin: Could not fetch http://pkgsrc.saveosx.org/Darwin/2014Q4/x86_64/All//pkg_summary.gz

**Comment by cmacrae** [comment]
We no longer host packages on the saveox.org domain.
These are now hosted by Joyent.
I recommend you remove your pkgsrc environment and re-run my bootstrap, as there have been some big changes.

To remove the stuff in place, delete the following files/directories:
/usr/pkg
/var/db/pkg*
/etc/paths.d/saveosx

Once you've removed these, run the latest bootstrap script, and you should be good to go :)
