### ISSUE TITLE
Checksum fails

### ISSUE THREAD

**Issue by biscuitpants** [cmacrae/saveosx#9]
When running the script the checksum on the SHA fails.

**Comment by cmacrae** [comment]
Thanks @biscuitpants - I just accepted [this pull request](https://github.com/cmacrae/saveosx/pull/7) that should resolve this. Could you pull the latest, try again, then get back to me?

**Comment by biscuitpants** [comment]
That was exceptionally fast! Thanks for the fix :)

**Comment by cmacrae** [comment]
Haha, it's not often I'm away from a computer ;) No problem - thanks for bringing this to my attention :+1:
